from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_pdf_report(
    *,
    case: dict,
    findings: list[dict],
) -> bytes:
    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title="AirScan Broadcast Compliance Report",
    )

    navy = colors.HexColor("#0A1628")
    gold = colors.HexColor("#F5A623")

    h1 = ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=16, textColor=navy, spaceAfter=8)
    h2 = ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=11, textColor=navy, spaceAfter=6)
    p = ParagraphStyle("p", fontName="Helvetica", fontSize=9, textColor=colors.black, leading=12)
    small = ParagraphStyle("small", fontName="Helvetica", fontSize=8, textColor=colors.grey)

    def ts(sec: float) -> str:
        sec = max(0, float(sec))
        m = int(sec // 60)
        s = int(sec % 60)
        return f"{m}:{s:02d}"

    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = (f.get("severity") or "").lower()
        if sev in counts:
            counts[sev] += 1

    story = []
    story.append(Paragraph("AirScan — Broadcast Compliance Report", h1))
    story.append(Paragraph("Generated for NBC Nigeria compliance monitoring", small))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Case information", h2))
    info_rows = [
        ["Station", case.get("station_name") or "—"],
        ["Program", case.get("program_name") or "—"],
        ["Date", case.get("broadcast_date") or "—"],
        ["File", case.get("file_name") or "—"],
        ["Duration", str(case.get("file_duration_seconds") or "—") + " sec"],
    ]
    info_table = Table(info_rows, colWidths=[35 * mm, 145 * mm])
    info_table.setStyle(
        TableStyle(
            [
                ("TEXTCOLOR", (0, 0), (-1, -1), navy),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(info_table)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Executive summary", h2))
    story.append(
        Paragraph(
            f"Total findings: <b>{len(findings)}</b> (Critical {counts['critical']}, High {counts['high']}, Medium {counts['medium']}, Low {counts['low']}).",
            p,
        )
    )
    story.append(Spacer(1, 10))

    story.append(Paragraph("Findings", h2))
    rows = [["Timestamp", "Quote", "Policy clause", "Severity", "Recommended action"]]
    for f in findings:
        rows.append(
            [
                f"{ts(f.get('timestamp_start', 0))}–{ts(f.get('timestamp_end', 0))}",
                (f.get("quote") or "").replace("\n", " ")[:220],
                f"{f.get('clause_section_number', '')} {f.get('clause_title', '')}".strip(),
                (f.get("severity") or "").title(),
                f.get("recommended_action") or "",
            ]
        )

    table = Table(rows, repeatRows=1, colWidths=[25 * mm, 60 * mm, 45 * mm, 20 * mm, 35 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), navy),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
                ("LINEABOVE", (0, 1), (-1, 1), 1, gold),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 10))

    story.append(Paragraph(f"Generated by AirScan · {datetime.utcnow().isoformat()}Z", small))

    doc.build(story)
    return buf.getvalue()
